"use client";

import { useReadContract } from "wagmi";
import { YIELD_OPTIMIZER_ADDRESS, ARMINA_POOL_ADDRESS } from "@/contracts/config";
import { ARMINA_YIELD_OPTIMIZER_ABI, ARMINA_POOL_ABI } from "@/contracts/abis";

const PROTOCOL_NAMES: Record<number, string> = {
  0: "None",
  1: "Moonwell",
  2: "Aave V3",
  3: "Compound V3",
  4: "Morpho",
  5: "Seamless",
};

/**
 * Read current APY from ArminaPool (queries optimizer if set)
 */
export function useCurrentAPY() {
  const { data, isLoading, error } = useReadContract({
    address: ARMINA_POOL_ADDRESS,
    abi: ARMINA_POOL_ABI as any,
    functionName: "getCurrentAPY",
    query: { enabled: !!ARMINA_POOL_ADDRESS },
  });

  return {
    apy: data ? Number(data as bigint) : 0, // basis points
    apyPercent: data ? Number(data as bigint) / 100 : 0, // percentage
    isLoading,
    error,
  };
}

/**
 * Read best protocol + APY from YieldOptimizer
 */
export function useBestProtocol() {
  const { data, isLoading, error } = useReadContract({
    address: YIELD_OPTIMIZER_ADDRESS,
    abi: ARMINA_YIELD_OPTIMIZER_ABI as any,
    functionName: "getBestAPY",
    query: { enabled: !!YIELD_OPTIMIZER_ADDRESS },
  });

  const result = data as [number, bigint] | undefined;

  return {
    protocol: result ? Number(result[0]) : 0,
    protocolName: result ? PROTOCOL_NAMES[Number(result[0])] || "Unknown" : "Loading...",
    apy: result ? Number(result[1]) : 0, // basis points
    apyPercent: result ? Number(result[1]) / 100 : 0,
    isLoading,
    error,
  };
}

/**
 * Read total deposited in optimizer
 */
export function useTotalDeposited() {
  const { data, isLoading, error } = useReadContract({
    address: YIELD_OPTIMIZER_ADDRESS,
    abi: ARMINA_YIELD_OPTIMIZER_ABI as any,
    functionName: "totalDeposited",
    query: { enabled: !!YIELD_OPTIMIZER_ADDRESS },
  });

  return {
    totalDeposited: (data as bigint) || BigInt(0),
    isLoading,
    error,
  };
}

/**
 * Read total yield generated by optimizer
 */
export function useTotalYieldGenerated() {
  const { data, isLoading, error } = useReadContract({
    address: YIELD_OPTIMIZER_ADDRESS,
    abi: ARMINA_YIELD_OPTIMIZER_ABI as any,
    functionName: "totalYieldGenerated",
    query: { enabled: !!YIELD_OPTIMIZER_ADDRESS },
  });

  return {
    totalYieldGenerated: (data as bigint) || BigInt(0),
    isLoading,
    error,
  };
}

/**
 * Read pool yield status from optimizer
 */
export function usePoolYieldStatus(poolAddress: `0x${string}` | undefined) {
  const { data, isLoading, error } = useReadContract({
    address: YIELD_OPTIMIZER_ADDRESS,
    abi: ARMINA_YIELD_OPTIMIZER_ABI as any,
    functionName: "getPoolYieldStatus",
    args: poolAddress ? [poolAddress] : undefined,
    query: { enabled: !!YIELD_OPTIMIZER_ADDRESS && !!poolAddress },
  });

  const result = data as [bigint, bigint, number, bigint, bigint] | undefined;

  return {
    totalDeposit: result ? result[0] : BigInt(0),
    currentYield: result ? result[1] : BigInt(0),
    currentProtocol: result ? Number(result[2]) : 0,
    currentProtocolName: result ? PROTOCOL_NAMES[Number(result[2])] || "None" : "None",
    currentAPY: result ? Number(result[3]) : 0,
    lastRebalance: result ? Number(result[4]) : 0,
    isLoading,
    error,
  };
}

/**
 * Read protocol info from optimizer
 */
export function useProtocolInfo(protocolId: number) {
  const { data, isLoading, error } = useReadContract({
    address: YIELD_OPTIMIZER_ADDRESS,
    abi: ARMINA_YIELD_OPTIMIZER_ABI as any,
    functionName: "protocols",
    args: [protocolId],
    query: { enabled: !!YIELD_OPTIMIZER_ADDRESS && protocolId > 0 },
  });

  const result = data as [string, string, bigint, bigint, boolean] | undefined;

  return {
    pool: result ? result[0] : "",
    aToken: result ? result[1] : "",
    currentAPY: result ? Number(result[2]) : 0,
    deposited: result ? result[3] : BigInt(0),
    isActive: result ? result[4] : false,
    protocolName: PROTOCOL_NAMES[protocolId] || "Unknown",
    isLoading,
    error,
  };
}

export { PROTOCOL_NAMES };
