export const ARMINA_FACTORY_ABI = [
  {
    inputs: [
      { internalType: "address", name: "_idrx", type: "address" },
      { internalType: "address", name: "_reputation", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "InvalidParticipantCount", type: "error" },
  { inputs: [], name: "InvalidTier", type: "error" },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  { inputs: [], name: "TierNotActive", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "previousOwner", type: "address" },
      { indexed: true, internalType: "address", name: "newOwner", type: "address" },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "poolId", type: "uint256" },
      { indexed: true, internalType: "address", name: "poolAddress", type: "address" },
      { indexed: true, internalType: "address", name: "creator", type: "address" },
      { indexed: false, internalType: "enum ArminaFactory.Tier", name: "tier", type: "uint8" },
    ],
    name: "PoolCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "enum ArminaFactory.Tier", name: "tier", type: "uint8" },
      {
        components: [
          { internalType: "uint256", name: "contribution", type: "uint256" },
          { internalType: "uint256", name: "minParticipants", type: "uint256" },
          { internalType: "uint256", name: "maxParticipants", type: "uint256" },
          { internalType: "uint256", name: "cycleDays", type: "uint256" },
          { internalType: "bool", name: "isActive", type: "bool" },
        ],
        indexed: false,
        internalType: "struct ArminaFactory.TierConfig",
        name: "config",
        type: "tuple",
      },
    ],
    name: "TierConfigUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "COLLATERAL_RATIO",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "enum ArminaFactory.Tier", name: "tier", type: "uint8" },
      { internalType: "uint256", name: "participantCount", type: "uint256" },
    ],
    name: "createPool",
    outputs: [{ internalType: "address", name: "poolAddress", type: "address" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getActivePools",
    outputs: [{ internalType: "uint256[]", name: "activePoolIds", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getOpenPools",
    outputs: [{ internalType: "uint256[]", name: "openPoolIds", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "poolId", type: "uint256" }],
    name: "getPoolDetails",
    outputs: [
      { internalType: "address", name: "poolAddress", type: "address" },
      { internalType: "uint256", name: "contribution", type: "uint256" },
      { internalType: "uint256", name: "maxParticipants", type: "uint256" },
      { internalType: "uint256", name: "currentParticipants", type: "uint256" },
      { internalType: "uint256", name: "currentRound", type: "uint256" },
      { internalType: "bool", name: "isActive", type: "bool" },
      { internalType: "bool", name: "isCompleted", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "user", type: "address" }],
    name: "getUserPools",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "idrx",
    outputs: [{ internalType: "contract IDRX", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "poolCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "pools",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "reputation",
    outputs: [{ internalType: "contract ArminaReputation", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "enum ArminaFactory.Tier", name: "tier", type: "uint8" },
      { internalType: "bool", name: "active", type: "bool" },
    ],
    name: "setTierActive",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "enum ArminaFactory.Tier", name: "", type: "uint8" }],
    name: "tierConfigs",
    outputs: [
      { internalType: "uint256", name: "contribution", type: "uint256" },
      { internalType: "uint256", name: "minParticipants", type: "uint256" },
      { internalType: "uint256", name: "maxParticipants", type: "uint256" },
      { internalType: "uint256", name: "cycleDays", type: "uint256" },
      { internalType: "bool", name: "isActive", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "enum ArminaFactory.Tier", name: "tier", type: "uint8" },
      {
        components: [
          { internalType: "uint256", name: "contribution", type: "uint256" },
          { internalType: "uint256", name: "minParticipants", type: "uint256" },
          { internalType: "uint256", name: "maxParticipants", type: "uint256" },
          { internalType: "uint256", name: "cycleDays", type: "uint256" },
          { internalType: "bool", name: "isActive", type: "bool" },
        ],
        internalType: "struct ArminaFactory.TierConfig",
        name: "config",
        type: "tuple",
      },
    ],
    name: "updateTierConfig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "userPools",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
